### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by teaktales** [gasser-ma/Cut-encoding-for-shaper-origin#1]
How can we install it in Inkscape?

**Comment by gasser-ma** [comment]
goto, and Download the zip file (klick on the Image)
[https://inkscape.org/~hosli/%E2%98%85cut-encoding-for-shaper-origin](https://inkscape.org/~hosli/%E2%98%85cut-encoding-for-shaper-origin)

read the instructions for manual Install under:
[https://inkscape.org/gallery/=extension/](https://inkscape.org/gallery/=extension/)
(
_"To manually install a new extension, download and unpack the archive file. Copy the files into the directory listed at Edit > Preferences > System: User extensions. After a restart of Inkscape, the new extension will be available."_
)


You find the extension in Inkscape under menu:
--> "Extensions" --> "Modify Path" --> "Cut encoding for origin"

i hope it helps.
and let me now if is there any bugs ;-)
